export const GET_DOWNLAOD_ALL_BOOK_TABLE = 'GET_DOWNLAOD_ALL_BOOK_TABLE';
export const GET_DOWNLAOD_ALL_BOOK_DATA = 'GET_DOWNLAOD_ALL_BOOK_DATA';
export const GET_DOWNLAOD_ALL_BOOK_STATE = 'GET_DOWNLAOD_ALL_BOOK_STATE';
